Built-in biome extraction and parsing
valence-rs/valence pull request #136
Opened 2022-10-23 22:30 UTC by TerminatorNL

This PR adds loading of built-in biomes and makes them accessible in Rust. This includes both the Java and Rust segment and this PR makes #135 obsolete.

The names inside biome.rs are not optimal, but do work.

After this PR, the next one will be [anvil](https://github.com/TerminatorNL/valence/tree/anvil) file loading support

I was not able to include /out/biome.rs since it would make this commit message too long. You can find it [here](https://discord.com/channels/998132822239870997/1033869808657252393/1033869808657252393)

2022-10-24 00:04 UTC, dyc3 commented
>I was not able to include /out/biome.rs

You should make a spoiler that contains the generated code: https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287

2022-10-24 01:39 UTC, rj00a commented
Made some adjustments. However, there are some more changes I would like to see:
- We should avoid making up our own categories like "weather" and "color". It ought to match the structure of [to_biome_registry_item](https://github.com/valence-rs/valence/blob/56ebcaf50d0dd705d49f0e9355d60c171f412178/src/biome.rs#L54). (Weather should probably be called "climate" but I digress.)
- The names of the generated types should also be consistent with the JSON. For instance, VanillaBiomeSpawnRates should be called `BiomeSpawnSettings` or something similar (maybe without the `Biome` prefix, idk)

2022-10-24 01:40 UTC, rj00a requested changes
Made some adjustments. However, there are some more changes I would like to see:
- We should avoid making up our own categories like "weather" and "color". It ought to match the structure of [to_biome_registry_item](https://github.com/valence-rs/valence/blob/56ebcaf50d0dd705d49f0e9355d60c171f412178/src/biome.rs#L54). (Weather should probably be called "climate" but I digress.)
- The names of the generated types should also be consistent with the JSON. For instance, VanillaBiomeSpawnRates should be called `BiomeSpawnSettings` or something similar (maybe without the `Biome` prefix, idk)

2022-10-24 20:01 UTC, TerminatorNL commented
That made a lot of sense! I actually did not notice valence already had a pretty well worked out biome.rs.

<details>
  <summary> /out/biome.rs</summary>

```rust
use std::str::FromStr;

use super::{Biome, BiomeGrassColorModifier, BiomePrecipitation};
use crate::ident::{Ident, IdentError};
#[derive(Debug, Clone, PartialEq, PartialOrd)]
pub struct SpawnProperty {
    pub name: &'static str,
    pub min_group_size: u32,
    pub max_group_size: u32,
    pub weight: i32,
}
#[derive(Debug, Clone, PartialEq, PartialOrd)]
pub struct SpawnSettings {
    pub probability: f32,
    pub ambient: &'static [SpawnProperty],
    pub axolotls: &'static [SpawnProperty],
    pub creature: &'static [SpawnProperty],
    pub misc: &'static [SpawnProperty],
    pub monster: &'static [SpawnProperty],
    pub underground_water_creature: &'static [SpawnProperty],
    pub water_ambient: &'static [SpawnProperty],
    pub water_creature: &'static [SpawnProperty],
}
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum BiomeKind {
    TheVoid = 0isize,
    Plains = 1isize,
    SunflowerPlains = 2isize,
    SnowyPlains = 3isize,
    IceSpikes = 4isize,
    Desert = 5isize,
    Swamp = 6isize,
    MangroveSwamp = 7isize,
    Forest = 8isize,
    FlowerForest = 9isize,
    BirchForest = 10isize,
    DarkForest = 11isize,
    OldGrowthBirchForest = 12isize,
    OldGrowthPineTaiga = 13isize,
    OldGrowthSpruceTaiga = 14isize,
    Taiga = 15isize,
    SnowyTaiga = 16isize,
    Savanna = 17isize,
    SavannaPlateau = 18isize,
    WindsweptHills = 19isize,
    WindsweptGravellyHills = 20isize,
    WindsweptForest = 21isize,
    WindsweptSavanna = 22isize,
    Jungle = 23isize,
    SparseJungle = 24isize,
    BambooJungle = 25isize,
    Badlands = 26isize,
    ErodedBadlands = 27isize,
    WoodedBadlands = 28isize,
    Meadow = 29isize,
    Grove = 30isize,
    SnowySlopes = 31isize,
    FrozenPeaks = 32isize,
    JaggedPeaks = 33isize,
    StonyPeaks = 34isize,
    River = 35isize,
    FrozenRiver = 36isize,
    Beach = 37isize,
    SnowyBeach = 38isize,
    StonyShore = 39isize,
    WarmOcean = 40isize,
    LukewarmOcean = 41isize,
    DeepLukewarmOcean = 42isize,
    Ocean = 43isize,
    DeepOcean = 44isize,
    ColdOcean = 45isize,
    DeepColdOcean = 46isize,
    FrozenOcean = 47isize,
    DeepFrozenOcean = 48isize,
    MushroomFields = 49isize,
    DripstoneCaves = 50isize,
    LushCaves = 51isize,
    DeepDark = 52isize,
    NetherWastes = 53isize,
    WarpedForest = 54isize,
    CrimsonForest = 55isize,
    SoulSandValley = 56isize,
    BasaltDeltas = 57isize,
    TheEnd = 58isize,
    EndHighlands = 59isize,
    EndMidlands = 60isize,
    SmallEndIslands = 61isize,
    EndBarrens = 62isize,
}
impl BiomeKind {
    #[doc = r" Constructs an `BiomeKind` from a raw biome ID."]
    #[doc = r""]
    #[doc = r" If the given ID is invalid, `None` is returned."]
    pub const fn from_raw(id: u16) -> Option<Self> {
        match id {
            0u16 => Some(Self::TheVoid),
            1u16 => Some(Self::Plains),
            2u16 => Some(Self::SunflowerPlains),
            3u16 => Some(Self::SnowyPlains),
            4u16 => Some(Self::IceSpikes),
            5u16 => Some(Self::Desert),
            6u16 => Some(Self::Swamp),
            7u16 => Some(Self::MangroveSwamp),
            8u16 => Some(Self::Forest),
            9u16 => Some(Self::FlowerForest),
            10u16 => Some(Self::BirchForest),
            11u16 => Some(Self::DarkForest),
            12u16 => Some(Self::OldGrowthBirchForest),
            13u16 => Some(Self::OldGrowthPineTaiga),
            14u16 => Some(Self::OldGrowthSpruceTaiga),
            15u16 => Some(Self::Taiga),
            16u16 => Some(Self::SnowyTaiga),
            17u16 => Some(Self::Savanna),
            18u16 => Some(Self::SavannaPlateau),
            19u16 => Some(Self::WindsweptHills),
            20u16 => Some(Self::WindsweptGravellyHills),
            21u16 => Some(Self::WindsweptForest),
            22u16 => Some(Self::WindsweptSavanna),
            23u16 => Some(Self::Jungle),
            24u16 => Some(Self::SparseJungle),
            25u16 => Some(Self::BambooJungle),
            26u16 => Some(Self::Badlands),
            27u16 => Some(Self::ErodedBadlands),
            28u16 => Some(Self::WoodedBadlands),
            29u16 => Some(Self::Meadow),
            30u16 => Some(Self::Grove),
            31u16 => Some(Self::SnowySlopes),
            32u16 => Some(Self::FrozenPeaks),
            33u16 => Some(Self::JaggedPeaks),
            34u16 => Some(Self::StonyPeaks),
            35u16 => Some(Self::River),
            36u16 => Some(Self::FrozenRiver),
            37u16 => Some(Self::Beach),
            38u16 => Some(Self::SnowyBeach),
            39u16 => Some(Self::StonyShore),
            40u16 => Some(Self::WarmOcean),
            41u16 => Some(Self::LukewarmOcean),
            42u16 => Some(Self::DeepLukewarmOcean),
            43u16 => Some(Self::Ocean),
            44u16 => Some(Self::DeepOcean),
            45u16 => Some(Self::ColdOcean),
            46u16 => Some(Self::DeepColdOcean),
            47u16 => Some(Self::FrozenOcean),
            48u16 => Some(Self::DeepFrozenOcean),
            49u16 => Some(Self::MushroomFields),
            50u16 => Some(Self::DripstoneCaves),
            51u16 => Some(Self::LushCaves),
            52u16 => Some(Self::DeepDark),
            53u16 => Some(Self::NetherWastes),
            54u16 => Some(Self::WarpedForest),
            55u16 => Some(Self::CrimsonForest),
            56u16 => Some(Self::SoulSandValley),
            57u16 => Some(Self::BasaltDeltas),
            58u16 => Some(Self::TheEnd),
            59u16 => Some(Self::EndHighlands),
            60u16 => Some(Self::EndMidlands),
            61u16 => Some(Self::SmallEndIslands),
            62u16 => Some(Self::EndBarrens),
            _ => None,
        }
    }
    #[doc = r" Returns the raw biome ID."]
    pub const fn to_raw(self) -> u16 {
        self as u16
    }
    pub fn from_ident<S: AsRef<str>>(ident: &Ident<S>) -> Option<Self> {
        if ident.namespace() != "minecraft" {
            return None;
        }
        match ident.path() {
            "the_void" => Some(Self::TheVoid),
            "plains" => Some(Self::Plains),
            "sunflower_plains" => Some(Self::SunflowerPlains),
            "snowy_plains" => Some(Self::SnowyPlains),
            "ice_spikes" => Some(Self::IceSpikes),
            "desert" => Some(Self::Desert),
            "swamp" => Some(Self::Swamp),
            "mangrove_swamp" => Some(Self::MangroveSwamp),
            "forest" => Some(Self::Forest),
            "flower_forest" => Some(Self::FlowerForest),
            "birch_forest" => Some(Self::BirchForest),
            "dark_forest" => Some(Self::DarkForest),
            "old_growth_birch_forest" => Some(Self::OldGrowthBirchForest),
            "old_growth_pine_taiga" => Some(Self::OldGrowthPineTaiga),
            "old_growth_spruce_taiga" => Some(Self::OldGrowthSpruceTaiga),
            "taiga" => Some(Self::Taiga),
            "snowy_taiga" => Some(Self::SnowyTaiga),
            "savanna" => Some(Self::Savanna),
            "savanna_plateau" => Some(Self::SavannaPlateau),
            "windswept_hills" => Some(Self::WindsweptHills),
            "windswept_gravelly_hills" => Some(Self::WindsweptGravellyHills),
            "windswept_forest" => Some(Self::WindsweptForest),
            "windswept_savanna" => Some(Self::WindsweptSavanna),
            "jungle" => Some(Self::Jungle),
            "sparse_jungle" => Some(Self::SparseJungle),
            "bamboo_jungle" => Some(Self::BambooJungle),
            "badlands" => Some(Self::Badlands),
            "eroded_badlands" => Some(Self::ErodedBadlands),
            "wooded_badlands" => Some(Self::WoodedBadlands),
            "meadow" => Some(Self::Meadow),
            "grove" => Some(Self::Grove),
            "snowy_slopes" => Some(Self::SnowySlopes),
            "frozen_peaks" => Some( [...]

2022-10-24 21:48 UTC, TerminatorNL commented
This will be moved into the `valence_anvil` crate.

2022-11-03 23:04 UTC, rj00a commented
Closing this because of #145

2022-11-03 23:04 UTC, closed without merging