Create marathon.rs example
valence-rs/valence pull request #28
Opened 2022-09-06 01:38 UTC by emortaldev

2022-09-06 02:27 UTC, emortaldev commented
I forgot to remove the separate world when the player leaves

2022-09-06 03:18 UTC, rj00a commented
> I forgot to remove the separate world when the player leaves

You can still push changes. Don't forget to `cargo fmt`.

2022-09-09 22:39 UTC, emortaldev commented
I believe this is ready, worlds are now unloaded when players leave

2022-09-10 05:59 UTC, rj00a requested changes
If you rebase with `main` you'll run into some issues.

Also `cargo clippy --example parkour`.

2022-09-10 05:59 UTC, rj00a commented on examples/parkour.rs
> +}
This could just be a `BlockPos`

2022-09-25 02:33 UTC, rj00a approved these changes

2022-09-25 02:40 UTC, merged