Solve inability for items with improper NBT data to be moved out of inventories
valence-rs/valence pull request #529
Opened 2023-09-20 05:30 UTC by Mac898

Hi,
# Objective

I was playing around with the chest example.
After adding a item with NBT data, I noticed I was unable to remove it from the chest.
Sourced the error down to this check. All I have done is not check the NBT data for now.

Same as in last comment of #292.

# Solution

Only item kind and count checked, nbt ignored.

Kind Regards,
Mac

2023-09-20 16:35 UTC, dyc3 requested changes
This needs a unit test.

2023-09-20 16:35 UTC, dyc3 commented on crates/valence_inventory/src/validate.rs
> +                        // on the item in the inventory.
nit

```suggestion
                        // There are some cases where the client will add NBT data that 
                        // did not previously exist.
```

2023-09-21 07:21 UTC, Mac898 commented
I've never written a unit test in rust, but I'll give it a go and try to follow the examples alrady in validate.rs :)

2023-09-21 08:17 UTC, Mac898 commented
I have verified the unit test fails on the old version, and passes after the changes.

Assuming all else is well, should be complete now.

2023-09-21 12:12 UTC, dyc3 approved these changes

2023-09-21 12:12 UTC, merged