Migrating the packets to wiki.vg
valence-rs/valence pull request #62
Opened 2022-09-14 20:28 UTC by EmperialDev

Migrating all the packet names to wiki.vg's insted of fabric's.

I have also copied the documentation from wiki.vg into the code as doc comments, so it's easier to see what the diffrent packets are for.

2022-09-14 21:22 UTC, rj00a commented
I would avoid documenting the packets because that info can become outdated/incorrect very easily. Also there is no need to change the field names.

As I merge other PRs there are going to be a lot of merge conflicts so apologies in advance.

2022-09-15 16:03 UTC, EmperialDev commented
That's okay. I will remove the documentation and just rename the packets.

2022-09-16 04:15 UTC, rj00a requested changes
- Packets that share identical names across groups should distinguish themselves with a suffix. For instance, `Disconnect` has login and play variants, so they should be named `DisconnectLogin` and `DisconnectPlay`.
- Packets that have the same name across serverbound and clientbound boundaries should be distinguished similarly with a `C2s` or `S2c` suffix.

Other than that looks good. Just need to `cargo fmt`.

2022-09-17 04:28 UTC, rj00a approved these changes

2022-09-17 04:29 UTC, merged