Expose enchantments to Rust
valence-rs/valence pull request #99
Opened 2022-10-02 13:39 UTC by TerminatorNL

This is a continuation of #93. But now we can expose the enchants in Rust.

Please have a look if this is the format you'd like to see, I am willing to change everything :+1:

Currently, all enchantments have a level field, but I included a docstring that informs developers about the vanilla-compatible levels.

If this PR is approved, we can implement functionality of enchants in [src/enchant.rs](https://github.com/valence-rs/valence/compare/main...TerminatorNL:enchantment-parser-rust?expand=1#diff-26da930a8457af3c2a733bb3502f558e1c8568120b9e4d175a384d6771692163). I left it blank for now because I am not sure if it's within the scope of Valence.

The following file is generated:
<details>
  <summary>/out/enchant.rs (Click to see contents)</summary>

```rust
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EnchantmentKind {
    Protection(ProtectionEnchantment),
    FireProtection(FireProtectionEnchantment),
    FeatherFalling(FeatherFallingEnchantment),
    BlastProtection(BlastProtectionEnchantment),
    ProjectileProtection(ProjectileProtectionEnchantment),
    Respiration(RespirationEnchantment),
    AquaAffinity(AquaAffinityEnchantment),
    Thorns(ThornsEnchantment),
    DepthStrider(DepthStriderEnchantment),
    FrostWalker(FrostWalkerEnchantment),
    BindingCurse(BindingCurseEnchantment),
    SoulSpeed(SoulSpeedEnchantment),
    SwiftSneak(SwiftSneakEnchantment),
    Sharpness(SharpnessEnchantment),
    Smite(SmiteEnchantment),
    BaneOfArthropods(BaneOfArthropodsEnchantment),
    Knockback(KnockbackEnchantment),
    FireAspect(FireAspectEnchantment),
    Looting(LootingEnchantment),
    Sweeping(SweepingEnchantment),
    Efficiency(EfficiencyEnchantment),
    SilkTouch(SilkTouchEnchantment),
    Unbreaking(UnbreakingEnchantment),
    Fortune(FortuneEnchantment),
    Power(PowerEnchantment),
    Punch(PunchEnchantment),
    Flame(FlameEnchantment),
    Infinity(InfinityEnchantment),
    LuckOfTheSea(LuckOfTheSeaEnchantment),
    Lure(LureEnchantment),
    Loyalty(LoyaltyEnchantment),
    Impaling(ImpalingEnchantment),
    Riptide(RiptideEnchantment),
    Channeling(ChannelingEnchantment),
    Multishot(MultishotEnchantment),
    QuickCharge(QuickChargeEnchantment),
    Piercing(PiercingEnchantment),
    Mending(MendingEnchantment),
    VanishingCurse(VanishingCurseEnchantment),
}
pub trait EnchantmentDescriptor: EnchantmentSource {
    const ID: u16;
    const NAME: &'static str;
    const TRANSLATION_KEY: &'static str;
    const MIN_LEVEL: i16;
    const MAX_LEVEL: i16;
    const IS_CURSE: bool;
    const RARITY_WEIGHT: i32;
}
pub trait EnchantmentSource {
    const TREASURE: bool;
    const ENCHANTMENT_TABLE: bool;
    const RANDOM_SELECTION: bool;
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ProtectionEnchantment {
    #[doc = "The level of this enchantment."]
    #[doc = "Vanilla minecraft supports levels 1..=4"]
    #[allow(unused)]
    level: i16,
}
impl EnchantmentDescriptor for ProtectionEnchantment {
    const ID: u16 = 0u16;
    const NAME: &'static str = "protection";
    const TRANSLATION_KEY: &'static str = "enchantment.minecraft.protection";
    const MIN_LEVEL: i16 = 1i16;
    const MAX_LEVEL: i16 = 4i16;
    const IS_CURSE: bool = false;
    const RARITY_WEIGHT: i32 = 10i32;
}
impl EnchantmentSource for ProtectionEnchantment {
    const TREASURE: bool = false;
    const ENCHANTMENT_TABLE: bool = true;
    const RANDOM_SELECTION: bool = true;
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct FireProtectionEnchantment {
    #[doc = "The level of this enchantment."]
    #[doc = "Vanilla minecraft supports levels 1..=4"]
    #[allow(unused)]
    level: i16,
}
impl EnchantmentDescriptor for FireProtectionEnchantment {
    const ID: u16 = 1u16;
    const NAME: &'static str = "fire_protection";
    const TRANSLATION_KEY: &'static str = "enchantment.minecraft.fire_protection";
    const MIN_LEVEL: i16 = 1i16;
    const MAX_LEVEL: i16 = 4i16;
    const IS_CURSE: bool = false;
    const RARITY_WEIGHT: i32 = 5i32;
}
impl EnchantmentSource for FireProtectionEnchantment {
    const TREASURE: bool = false;
    const ENCHANTMENT_TABLE: bool = true;
    const RANDOM_SELECTION: bool = true;
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct FeatherFallingEnchantment {
    #[doc = "The level of this enchantment."]
    #[doc = "Vanilla minecraft supports levels 1..=4"]
    #[allow(unused)]
    level: i16,
}
impl EnchantmentDescriptor for FeatherFallingEnchantment {
    const ID: u16 = 2u16;
    const NAME: &'static str = "feather_falling";
    const TRANSLATION_KEY: &'static str = "enchantment.minecraft.feather_falling";
    const MIN_LEVEL: i16 = 1i16;
    const MAX_LEVEL: i16 = 4i16;
    const IS_CURSE: bool = false;
    const RARITY_WEIGHT: i32 = 5i32;
}
impl EnchantmentSource for FeatherFallingEnchantment {
    const TREASURE: bool = false;
    const ENCHANTMENT_TABLE: bool = true;
    const RANDOM_SELECTION: bool = true;
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlastProtectionEnchantment {
    #[doc = "The level of this enchantment."]
    #[doc = "Vanilla minecraft supports levels 1..=4"]
    #[allow(unused)]
    level: i16,
}
impl EnchantmentDescriptor for BlastProtectionEnchantment {
    const ID: u16 = 3u16;
    const NAME: &'static str = "blast_protection";
    const TRANSLATION_KEY: &'static str = "enchantment.minecraft.blast_protection";
    const MIN_LEVEL: i16 = 1i16;
    const MAX_LEVEL: i16 = 4i16;
    const IS_CURSE: bool = false;
    const RARITY_WEIGHT: i32 = 2i32;
}
impl EnchantmentSource for BlastProtectionEnchantment {
    const TREASURE: bool = false;
    const ENCHANTMENT_TABLE: bool = true;
    const RANDOM_SELECTION: bool = true;
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ProjectileProtectionEnchantment {
    #[doc = "The level of this enchantment."]
    #[doc = "Vanilla minecraft supports levels 1..=4"]
    #[allow(unused)]
    level: i16,
}
impl EnchantmentDescriptor for ProjectileProtectionEnchantment {
    const ID: u16 = 4u16;
    const NAME: &'static str = "projectile_protection";
    const TRANSLATION_KEY: &'static str = "enchantment.minecraft.projectile_protection";
    const MIN_LEVEL: i16 = 1i16;
    const MAX_LEVEL: i16 = 4i16;
    const IS_CURSE: bool = false;
    const RARITY_WEIGHT: i32 = 5i32;
}
impl EnchantmentSource for ProjectileProtectionEnchantment {
    const TREASURE: bool = false;
    const ENCHANTMENT_TABLE: bool = true;
    const RANDOM_SELECTION: bool = true;
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RespirationEnchantment {
    #[doc = "The level of this enchantment."]
    #[doc = "Vanilla minecraft supports levels 1..=3"]
    #[allow(unused)]
    level: i16,
}
impl EnchantmentDescriptor for RespirationEnchantment {
    const ID: u16 = 5u16;
    const NAME: &'static str = "respiration";
    const TRANSLATION_KEY: &'static str = "enchantment.minecraft.respiration";
    const MIN_LEVEL: i16 = 1i16;
    const MAX_LEVEL: i16 = 3i16;
    const IS_CURSE: bool = false;
    const RARITY_WEIGHT: i32 = 2i32;
}
impl EnchantmentSource for RespirationEnchantment {
    const TREASURE: bool = false;
    const ENCHANTMENT_TABLE: bool = true;
    const RANDOM_SELECTION: bool = true;
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct AquaAffinityEnchantment {
    #[doc = "The level of this enchantment."]
    #[doc = "Warning: Vanilla minecraft only supports level 1."]
    #[allow(unused)]
    level: i16,
}
impl EnchantmentDescriptor for AquaAffinityEnchantment {
    const ID: u16 = 6u16;
    const NAME: &'static str = "aqua_affinity";
    const TRANSLATION_KEY: &'static str = "enchantment.minecraft.aqua_affinity";
    const MIN_LEVEL: i16 = 1i16;
    const MAX_LEVEL: i16 = 1i16;
    const IS_CURSE: bool = false;
    const RARITY_WEIGHT: i32 = 2i32;
}
impl EnchantmentSource for AquaAffinity [...]

2022-10-02 16:20 UTC, dyc3 approved these changes
Seems good to me.

Regarding valence's scope: Providing utility functions to work with enchantments easier? Totally in scope. Replicating vanilla minecraft behavior to implement a specific enchantment? Out of scope.

2022-10-02 20:23 UTC, rj00a requested changes
I think the generated module would be better structured like this:
- An enum named `EnchantmentKind` whose variants contain no extra data. The discriminant of this enum is the enchantment ID used in the protocol. Note that I'm following the Rust stdlib convention of naming these field-less enums with a `Kind` suffix. See [`io::ErrorKind`](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html).
- `const fn`s on `EnchantmentKind` that return the extracted data for the particular enchantment.

This way you don't have to carry around a `level` field if you're just looking to identify enchantment types. It also makes the traits unnecessary.

Perhaps an `Echantment` type providing an `EnchantmentKind` can be defined in this module or downstream at a later date if it is needed.

2022-10-02 21:51 UTC, TerminatorNL commented
The generated file is now as follows:
<details>
  <summary>/out/enchant.rs (Click to see contents)</summary>

```rust
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EnchantmentKind {
    Protection = 0isize,
    FireProtection = 1isize,
    FeatherFalling = 2isize,
    BlastProtection = 3isize,
    ProjectileProtection = 4isize,
    Respiration = 5isize,
    AquaAffinity = 6isize,
    Thorns = 7isize,
    DepthStrider = 8isize,
    FrostWalker = 9isize,
    BindingCurse = 10isize,
    SoulSpeed = 11isize,
    SwiftSneak = 12isize,
    Sharpness = 13isize,
    Smite = 14isize,
    BaneOfArthropods = 15isize,
    Knockback = 16isize,
    FireAspect = 17isize,
    Looting = 18isize,
    Sweeping = 19isize,
    Efficiency = 20isize,
    SilkTouch = 21isize,
    Unbreaking = 22isize,
    Fortune = 23isize,
    Power = 24isize,
    Punch = 25isize,
    Flame = 26isize,
    Infinity = 27isize,
    LuckOfTheSea = 28isize,
    Lure = 29isize,
    Loyalty = 30isize,
    Impaling = 31isize,
    Riptide = 32isize,
    Channeling = 33isize,
    Multishot = 34isize,
    QuickCharge = 35isize,
    Piercing = 36isize,
    Mending = 37isize,
    VanishingCurse = 38isize,
}
impl EnchantmentKind {
    #[doc = r" Constructs an `EnchantmentKind` from a raw enchantment ID."]
    #[doc = r""]
    #[doc = r" If the given ID is invalid, `None` is returned."]
    pub const fn from_raw(id: u16) -> Option<Self> {
        match id {
            0u16 => Some(Self::Protection),
            1u16 => Some(Self::FireProtection),
            2u16 => Some(Self::FeatherFalling),
            3u16 => Some(Self::BlastProtection),
            4u16 => Some(Self::ProjectileProtection),
            5u16 => Some(Self::Respiration),
            6u16 => Some(Self::AquaAffinity),
            7u16 => Some(Self::Thorns),
            8u16 => Some(Self::DepthStrider),
            9u16 => Some(Self::FrostWalker),
            10u16 => Some(Self::BindingCurse),
            11u16 => Some(Self::SoulSpeed),
            12u16 => Some(Self::SwiftSneak),
            13u16 => Some(Self::Sharpness),
            14u16 => Some(Self::Smite),
            15u16 => Some(Self::BaneOfArthropods),
            16u16 => Some(Self::Knockback),
            17u16 => Some(Self::FireAspect),
            18u16 => Some(Self::Looting),
            19u16 => Some(Self::Sweeping),
            20u16 => Some(Self::Efficiency),
            21u16 => Some(Self::SilkTouch),
            22u16 => Some(Self::Unbreaking),
            23u16 => Some(Self::Fortune),
            24u16 => Some(Self::Power),
            25u16 => Some(Self::Punch),
            26u16 => Some(Self::Flame),
            27u16 => Some(Self::Infinity),
            28u16 => Some(Self::LuckOfTheSea),
            29u16 => Some(Self::Lure),
            30u16 => Some(Self::Loyalty),
            31u16 => Some(Self::Impaling),
            32u16 => Some(Self::Riptide),
            33u16 => Some(Self::Channeling),
            34u16 => Some(Self::Multishot),
            35u16 => Some(Self::QuickCharge),
            36u16 => Some(Self::Piercing),
            37u16 => Some(Self::Mending),
            38u16 => Some(Self::VanishingCurse),
            _ => None,
        }
    }
    #[doc = r" Returns the enchantment ID."]
    pub const fn id(&self) -> u16 {
        match &self {
            Self::Protection => 0u16,
            Self::FireProtection => 1u16,
            Self::FeatherFalling => 2u16,
            Self::BlastProtection => 3u16,
            Self::ProjectileProtection => 4u16,
            Self::Respiration => 5u16,
            Self::AquaAffinity => 6u16,
            Self::Thorns => 7u16,
            Self::DepthStrider => 8u16,
            Self::FrostWalker => 9u16,
            Self::BindingCurse => 10u16,
            Self::SoulSpeed => 11u16,
            Self::SwiftSneak => 12u16,
            Self::Sharpness => 13u16,
            Self::Smite => 14u16,
            Self::BaneOfArthropods => 15u16,
            Self::Knockback => 16u16,
            Self::FireAspect => 17u16,
            Self::Looting => 18u16,
            Self::Sweeping => 19u16,
            Self::Efficiency => 20u16,
            Self::SilkTouch => 21u16,
            Self::Unbreaking => 22u16,
            Self::Fortune => 23u16,
            Self::Power => 24u16,
            Self::Punch => 25u16,
            Self::Flame => 26u16,
            Self::Infinity => 27u16,
            Self::LuckOfTheSea => 28u16,
            Self::Lure => 29u16,
            Self::Loyalty => 30u16,
            Self::Impaling => 31u16,
            Self::Riptide => 32u16,
            Self::Channeling => 33u16,
            Self::Multishot => 34u16,
            Self::QuickCharge => 35u16,
            Self::Piercing => 36u16,
            Self::Mending => 37u16,
            Self::VanishingCurse => 38u16,
        }
    }
    #[doc = r" Returns the translation key."]
    pub const fn translation_key(&self) -> &'static str {
        match &self {
            Self::Protection => "enchantment.minecraft.protection",
            Self::FireProtection => "enchantment.minecraft.fire_protection",
            Self::FeatherFalling => "enchantment.minecraft.feather_falling",
            Self::BlastProtection => "enchantment.minecraft.blast_protection",
            Self::ProjectileProtection => "enchantment.minecraft.projectile_protection",
            Self::Respiration => "enchantment.minecraft.respiration",
            Self::AquaAffinity => "enchantment.minecraft.aqua_affinity",
            Self::Thorns => "enchantment.minecraft.thorns",
            Self::DepthStrider => "enchantment.minecraft.depth_strider",
            Self::FrostWalker => "enchantment.minecraft.frost_walker",
            Self::BindingCurse => "enchantment.minecraft.binding_curse",
            Self::SoulSpeed => "enchantment.minecraft.soul_speed",
            Self::SwiftSneak => "enchantment.minecraft.swift_sneak",
            Self::Sharpness => "enchantment.minecraft.sharpness",
            Self::Smite => "enchantment.minecraft.smite",
            Self::BaneOfArthropods => "enchantment.minecraft.bane_of_arthropods",
            Self::Knockback => "enchantment.minecraft.knockback",
            Self::FireAspect => "enchantment.minecraft.fire_aspect",
            Self::Looting => "enchantment.minecraft.looting",
            Self::Sweeping => "enchantment.minecraft.sweeping",
            Self::Efficiency => "enchantment.minecraft.efficiency",
            Self::SilkTouch => "enchantment.minecraft.silk_touch",
            Self::Unbreaking => "enchantment.minecraft.unbreaking",
            Self::Fortune => "enchantment.minecraft.fortune",
            Self::Power => "enchantment.minecraft.power",
            Self::Punch => "enchantment.minecraft.punch",
            Self::Flame => "enchantment.minecraft.flame",
            Self::Infinity => "enchantment.minecraft.infinity",
            Self::LuckOfTheSea => "enchantment.minecraft.luck_of_the_sea",
            Self::Lure => "enchantment.minecraft.lure",
            Self::Loyalty => "enchantment.minecraft.loyalty",
            Self::Impaling => "enchantment.minecraft.impaling",
            Self::Riptide => "enchantment.minecraft.riptide",
            Self::Channeling => "enchantment.minecraft.channeling",
            Self::Multishot => "enchantment.minecraft.multishot",
            Self::QuickCharge => "enchantment.minecraft.quick_charge",
            Self::Piercing => "enchantment.minecraft.piercing",
            Self::Mending => "enchantment.minecraft.mending",
            Self::VanishingCurse => "enchantment.minecraft.vanishing_curse",
        }
    }
    #[doc = r" Returns the enchantment name the game uses."]
    pub const fn name(&self) -> &'static str {
        match &self {
            Self::Protection => "protection",
            Self::FireProtection => "fire_protection",
            Self::FeatherFalling => "feather_falling",
            Self::BlastProtection => "blast_protection",
            Self::ProjectileProtec [...]

2022-10-02 22:36 UTC, rj00a requested changes
- The `EnchantmentKind` type should derive `Copy`.
- Because it derives `Copy`, the associated functions can take `self` instead of `&self`.
- Because the discriminant of the `EnchantmentKind` enum is its ID, the `id` function can be implemented as `self as u16`.
- Some formatting nitpicks.

2022-10-02 22:36 UTC, rj00a commented on build/enchant.rs
> +        impl EnchantmentKind{
```suggestion
        impl EnchantmentKind {
```

2022-10-02 22:36 UTC, rj00a commented on build/enchant.rs
> +        pub enum EnchantmentKind{
```suggestion
        pub enum EnchantmentKind {
```

2022-10-02 23:31 UTC, rj00a commented
And to match the structure of the JSON file it might be nice to have
```rust
impl EnchantmentKind {
    // ...
    pub const fn sources(self) -> EnchantmentSources { ... }
}

#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct EnchantmentSources {
    pub treasure: bool,
    pub enchantment: bool,
    pub random_source: bool,
}
```

2022-10-03 19:43 UTC, TerminatorNL commented
I updated the commit message. At it's current state, the following Rust code is generated:
<details>
  <summary>/out/enchant.rs (Click to see contents)</summary>

```rust
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct EnchantmentSources {
    pub treasure: bool,
    pub enchantment_table: bool,
    pub random_selection: bool,
}
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EnchantmentKind {
    Protection = 0isize,
    FireProtection = 1isize,
    FeatherFalling = 2isize,
    BlastProtection = 3isize,
    ProjectileProtection = 4isize,
    Respiration = 5isize,
    AquaAffinity = 6isize,
    Thorns = 7isize,
    DepthStrider = 8isize,
    FrostWalker = 9isize,
    BindingCurse = 10isize,
    SoulSpeed = 11isize,
    SwiftSneak = 12isize,
    Sharpness = 13isize,
    Smite = 14isize,
    BaneOfArthropods = 15isize,
    Knockback = 16isize,
    FireAspect = 17isize,
    Looting = 18isize,
    Sweeping = 19isize,
    Efficiency = 20isize,
    SilkTouch = 21isize,
    Unbreaking = 22isize,
    Fortune = 23isize,
    Power = 24isize,
    Punch = 25isize,
    Flame = 26isize,
    Infinity = 27isize,
    LuckOfTheSea = 28isize,
    Lure = 29isize,
    Loyalty = 30isize,
    Impaling = 31isize,
    Riptide = 32isize,
    Channeling = 33isize,
    Multishot = 34isize,
    QuickCharge = 35isize,
    Piercing = 36isize,
    Mending = 37isize,
    VanishingCurse = 38isize,
}
impl EnchantmentKind {
    #[doc = r" Constructs an `EnchantmentKind` from a raw enchantment ID."]
    #[doc = r""]
    #[doc = r" If the given ID is invalid, `None` is returned."]
    pub const fn from_raw(id: u16) -> Option<Self> {
        match id {
            0u16 => Some(Self::Protection),
            1u16 => Some(Self::FireProtection),
            2u16 => Some(Self::FeatherFalling),
            3u16 => Some(Self::BlastProtection),
            4u16 => Some(Self::ProjectileProtection),
            5u16 => Some(Self::Respiration),
            6u16 => Some(Self::AquaAffinity),
            7u16 => Some(Self::Thorns),
            8u16 => Some(Self::DepthStrider),
            9u16 => Some(Self::FrostWalker),
            10u16 => Some(Self::BindingCurse),
            11u16 => Some(Self::SoulSpeed),
            12u16 => Some(Self::SwiftSneak),
            13u16 => Some(Self::Sharpness),
            14u16 => Some(Self::Smite),
            15u16 => Some(Self::BaneOfArthropods),
            16u16 => Some(Self::Knockback),
            17u16 => Some(Self::FireAspect),
            18u16 => Some(Self::Looting),
            19u16 => Some(Self::Sweeping),
            20u16 => Some(Self::Efficiency),
            21u16 => Some(Self::SilkTouch),
            22u16 => Some(Self::Unbreaking),
            23u16 => Some(Self::Fortune),
            24u16 => Some(Self::Power),
            25u16 => Some(Self::Punch),
            26u16 => Some(Self::Flame),
            27u16 => Some(Self::Infinity),
            28u16 => Some(Self::LuckOfTheSea),
            29u16 => Some(Self::Lure),
            30u16 => Some(Self::Loyalty),
            31u16 => Some(Self::Impaling),
            32u16 => Some(Self::Riptide),
            33u16 => Some(Self::Channeling),
            34u16 => Some(Self::Multishot),
            35u16 => Some(Self::QuickCharge),
            36u16 => Some(Self::Piercing),
            37u16 => Some(Self::Mending),
            38u16 => Some(Self::VanishingCurse),
            _ => None,
        }
    }
    #[doc = r" Returns the enchantment ID."]
    pub const fn id(self) -> u16 {
        match self {
            Self::Protection => 0u16,
            Self::FireProtection => 1u16,
            Self::FeatherFalling => 2u16,
            Self::BlastProtection => 3u16,
            Self::ProjectileProtection => 4u16,
            Self::Respiration => 5u16,
            Self::AquaAffinity => 6u16,
            Self::Thorns => 7u16,
            Self::DepthStrider => 8u16,
            Self::FrostWalker => 9u16,
            Self::BindingCurse => 10u16,
            Self::SoulSpeed => 11u16,
            Self::SwiftSneak => 12u16,
            Self::Sharpness => 13u16,
            Self::Smite => 14u16,
            Self::BaneOfArthropods => 15u16,
            Self::Knockback => 16u16,
            Self::FireAspect => 17u16,
            Self::Looting => 18u16,
            Self::Sweeping => 19u16,
            Self::Efficiency => 20u16,
            Self::SilkTouch => 21u16,
            Self::Unbreaking => 22u16,
            Self::Fortune => 23u16,
            Self::Power => 24u16,
            Self::Punch => 25u16,
            Self::Flame => 26u16,
            Self::Infinity => 27u16,
            Self::LuckOfTheSea => 28u16,
            Self::Lure => 29u16,
            Self::Loyalty => 30u16,
            Self::Impaling => 31u16,
            Self::Riptide => 32u16,
            Self::Channeling => 33u16,
            Self::Multishot => 34u16,
            Self::QuickCharge => 35u16,
            Self::Piercing => 36u16,
            Self::Mending => 37u16,
            Self::VanishingCurse => 38u16,
        }
    }
    #[doc = r" Returns the translation key."]
    pub const fn translation_key(self) -> &'static str {
        match self {
            Self::Protection => "enchantment.minecraft.protection",
            Self::FireProtection => "enchantment.minecraft.fire_protection",
            Self::FeatherFalling => "enchantment.minecraft.feather_falling",
            Self::BlastProtection => "enchantment.minecraft.blast_protection",
            Self::ProjectileProtection => "enchantment.minecraft.projectile_protection",
            Self::Respiration => "enchantment.minecraft.respiration",
            Self::AquaAffinity => "enchantment.minecraft.aqua_affinity",
            Self::Thorns => "enchantment.minecraft.thorns",
            Self::DepthStrider => "enchantment.minecraft.depth_strider",
            Self::FrostWalker => "enchantment.minecraft.frost_walker",
            Self::BindingCurse => "enchantment.minecraft.binding_curse",
            Self::SoulSpeed => "enchantment.minecraft.soul_speed",
            Self::SwiftSneak => "enchantment.minecraft.swift_sneak",
            Self::Sharpness => "enchantment.minecraft.sharpness",
            Self::Smite => "enchantment.minecraft.smite",
            Self::BaneOfArthropods => "enchantment.minecraft.bane_of_arthropods",
            Self::Knockback => "enchantment.minecraft.knockback",
            Self::FireAspect => "enchantment.minecraft.fire_aspect",
            Self::Looting => "enchantment.minecraft.looting",
            Self::Sweeping => "enchantment.minecraft.sweeping",
            Self::Efficiency => "enchantment.minecraft.efficiency",
            Self::SilkTouch => "enchantment.minecraft.silk_touch",
            Self::Unbreaking => "enchantment.minecraft.unbreaking",
            Self::Fortune => "enchantment.minecraft.fortune",
            Self::Power => "enchantment.minecraft.power",
            Self::Punch => "enchantment.minecraft.punch",
            Self::Flame => "enchantment.minecraft.flame",
            Self::Infinity => "enchantment.minecraft.infinity",
            Self::LuckOfTheSea => "enchantment.minecraft.luck_of_the_sea",
            Self::Lure => "enchantment.minecraft.lure",
            Self::Loyalty => "enchantment.minecraft.loyalty",
            Self::Impaling => "enchantment.minecraft.impaling",
            Self::Riptide => "enchantment.minecraft.riptide",
            Self::Channeling => "enchantment.minecraft.channeling",
            Self::Multishot => "enchantment.minecraft.multishot",
            Self::QuickCharge => "enchantment.minecraft.quick_charge",
            Self::Piercing => "enchantment.minecraft.piercing",
            Self::Mending => "enchantment.minecraft.mending",
            Self::VanishingCurse => "enchantment.minecraft.vanishing_curse",
        }
    }
    #[doc = r" Returns the enchantment name the game uses."]
    pub const fn name(self) -> &'static str {
        match self {
    [...]

2022-10-03 19:49 UTC, dyc3 commented
> Question: Should we replace the following block with `EnchantmentSources::new(bool, bool, bool)` calls? It would reduce file size, but will be (slightly) harder to read.

Tbh, I don't think we care about file size. If anything, it might increase compile times, but I'd imagine that would be negligible. Regardless, leave those blocks as is because its easier to read.

2022-10-03 20:18 UTC, rj00a approved these changes

2022-10-03 20:19 UTC, merged